### PR TITLE
New feature: interiorToExterior

### PR DESCRIPTION
**Pull request by stanleyqubit**
This was fun working on.

Well the first obstacle I realized is that we can't determine interior type from outside. The cell has to be loaded first. Then we need to gather the data, and then we need to store that data, somewhere. Storing it as `tempData` is no fun, because the next time you load your save, you won't be able to hear anything because the data is lost. So I took the liberty of storing that data in `tes3.player.data` so that it persists across saves. Unless you have a different idea.

The one and only requirement for this to work is that the interior must have been visited beforehand. Once the cell has been visited, its door will always play in accordance to its interior type, so no need to worry about revisiting it ever again.

`interiorToExterior.lua` is strictly tied to the IA module, won't work without it, and it needs it so that our data updates every time an interior is visited.

### CODE REVIEW

**Comment by tewlwolow** [comment]
Good job! I'm just wondering.

Why can't we determine interior type before the cell loads? I've parsed cell statics from `nonDynamicData` before, e.g.:

```lua
function helper.getRandomCellRefPositions()
	local teleportCell = table.choice(tes3.dataHandler.nonDynamicData.cells)
	local positions = {}
	for ref in teleportCell:iterateReferences() do
		if ref.position then
			local pos = ref.position
			table.insert(positions, pos)
		end
	end
	return teleportCell, positions
end
```

[Source](https://github.com/tewlwolow/Happenstance-Hodokinesis/blob/be952a641605cd5e0b4a18e6100a6f16c6f6a199/Data%20Files/MWSE/mods/tew/Happenstance%20Hodokinesis/helper.lua#L326-L336)

Shouldn't this be enough? If we need cell names, statics, and NPC objects then all we need is there. Get the cell object from `destination` field on door reference, and then map to `nonDynamicData` if it's not available otherwise.

**Comment by stanleyqubit** [comment]
I've checked, unfortunately it seems that `tes3static` objects aren't available before the cell has been loaded. Your code snippet iterates over all available object types in the cell, and it might catch something other than `tes3static`, assuming you've not visited that cell before. You can check by starting a new game and try catching `tes3.objectType.static` refs from a cell you haven't yet visited.

NPC objects are indeed there, but they don't have mobile objects attached. You can access `isDead` directly on their refs, but I don't think it's very reliable that way. But since we don't have access to the statics in the first place, it's a dead end.

The game does save some cell data across saves from cells you've visited, but it doesn't save enough.

**Comment by stanleyqubit** [comment]
Added bridge from interior to interior. Imagine Vivec Plaza, there are shops and guilds there. You're in the Plaza, you hear the interiors for each shop on the doors. You go inside the shop, you hear the Plaza interior on the exit doors.

**Comment by stanleyqubit** [comment]
Just found out about [reference lifetime](https://github.com/MWSE/MWSE/commit/6df97d57edd0a94f10a2c8c3442573d520cfe7aa).

>The reference objects exist for 72 in-game hours after their containing cell is unloaded.

So NPCs only have mobile objects attached for 72 hours after you leave their cell. I'm going to refactor this a bit. 😁

**Comment by tewlwolow** [comment]
They didn't make it easy for us, did they... let me know when you're ready :)

**Comment by tewlwolow** [comment]
Note (from Hrn in MMC):

> - It's mobile actors that expire after 72 hours of not being visited. Temporary tes3references expire when they are unloaded from the cell cache. However, all NPCs are permanent references and are available for access.

**Comment by stanleyqubit** [comment]
>a bit.

_A bit_ more. This got intertwined with a bunch of other stuff I was working on. Almost done!

Ya, what Hrn said is spot on. I learned that by sheer accident just when I needed it haha.

**Comment by stanleyqubit** [comment]
Closed in favor of [10](https://github.com/tewlwolow/AURA/pull/10)

**Pull request closed without merging**
